######################################################################
# script to read output text files generated by the combine commands #
######################################################################
import os
import sys

def readr(filename):
    ### read signal strength (r) from the output of a combine command direct to a file
    r = 0.
    uperror = 0.
    downerror = 0.
    with open(filename,'r') as f:
	for l in f.readlines():
	    if l[:11]=='Best fit r:':
		l = l.replace('Best fit r: ','').replace(' (68% CL)','')
		l = l.split(' ')
		r = l[0]
		uperror = l[2].split('/')[1].strip('+')
		downerror = l[2].split('/')[0].strip('-')
    return (float(r),float(uperror),float(downerror))

def formatline(title,value,uperror,downerror):
    titlelen = 25
    numlen = 8
    res = str('{:<'+str(titlelen)+'}').format(title)
    res += ':'
    res += str('{:<'+str(numlen)+'}').format(str('{:.'+str(numlen-3)+'f}').format(value))
    res += '+'
    res += str('{:<'+str(numlen)+'}').format(str('{:.'+str(numlen-3)+'f}').format(uperror))
    res += '-'
    res += str('{:<'+str(numlen)+'}').format(str('{:.'+str(numlen-3)+'f}').format(downerror))
    res += '\n'
    res += '-'*(titlelen+3*numlen)+'\n'
    return res

if __name__=='__main__':

    datacarddir = ''
    if len(sys.argv)==2:
	datacarddir = sys.argv[1]
    else:
	print('### ERROR ###: need one command line argument.')
	print('               normal use: python readoutput.py <datacard directory>')

    outputfiles = sorted([f for f in os.listdir(datacarddir) if f[-8:]=='_out.txt'])
    reslist = []
    for f in outputfiles:
	(r,uperror,downerror) = readr(os.path.join(datacarddir,f))
	reslist.append({'card':f.replace('datacard_','').replace('dc_combined','').replace('_out.txt',''),
			'r':r,'uperror':uperror,'downerror':downerror})
    for res in reslist:
	print(formatline(res['card'],res['r'],res['uperror'],res['downerror']))
